### ISSUE TITLE
Container/row/column template

### ISSUE THREAD

**Issue by Duhduh1973** [bodiam/intellij-bootstrap3#29]
I was thinking a full snippet of this would be super helpful, ie:

You could type "bs3-crc" (container/row/column) or whatever and get:

<div class="container">
	<div class="row">
		<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
			
		</div>
	</div>
</div>

**Comment by bodiam** [comment]
Ah, sorry, I missed this issue! I'll add it in the new version! Thanks for the feedback.

**Comment by fcools** [comment]
I hope it's just an addition as you say.
In my projects I almost never have the need for an (extra) container as a parent for rows since the content (which contains other HTML before the rows) is in a div.container already.
However, I do agree a bs3-rc:* might com in handy since a .col requires a .row (or .form-group) as a parent.

**Comment by bodiam** [comment]
Well, I'm also a bit hesitant about the container thing, and also about using crypt abbreviations like this. If you really want this, just add it yourself. No need to add it to the plugin then. 

Let me know what your ideas are, and come up with an idea which is the most useful. I'm open to almost all ideas, so if you want a crc template, and it doesn't hurt the other 15000 installations, then why not.

**Comment by bodiam** [comment]
I thought about it a bit more, and won't implement it. If you still think it's needed, please make a pull request.
