### ISSUE TITLE
PHPStorm 9.0.2

### ISSUE THREAD

**Issue by dmachiavello** [bodiam/intellij-bootstrap3#30]
Not sure if this is the right place to add this issue, but either using the bs3-template:html5 or the bs3-cdn short cuts are still giving an old version of bootstrap and not the latest version (3.3.5). 

I've tried uninstalling and re-installing the plugins (with restarts). 

Here's a screencast of the issue: http://screencast.com/t/QJ1FDooC

Version screenshot: http://screencast.com/t/3Fwitxlj

**Comment by bodiam** [comment]
Hi @dmachiavello, interesting issue. I checked it for you, but here it works with 3.3.5. What happens when you go to Editor -> Live Templates -> Bootstrap3? Does the template there say 3.1.0? Or 3.3.5? What might help is to uninstall it (again), remove the templates from the live templates, and reinstall it again.

**Comment by bodiam** [comment]
Hi @dmachiavello , I'm closing this issue. If you're still suffering from the issue, please let me know.

**Comment by dmachiavello** [comment]
Thanks, sorry for the delay, i've have several machines and only one of them had this issue. Apparently there were two competing live templates "Bootstrap3" and "bootstrap3jade", after completely removing everything, restarting, then re-installing it looks like it worked. Thanks again for your help!
